### ISSUE TITLE
pull-scroll is not working in Firefox

### ISSUE THREAD

**Issue by evbogue** [dominictarr/pull-scroll#17]
See issue: https://github.com/evbogue/minbase/issues/1

There are no errors, the scroll bar just doesn't appear. 

The work around for this right now is to use Chrome/ium or Electron.

**Comment by dominictarr** [comment]
if you `browserify | indexhtmlify` the pull-scroll examples, do they work in ff?

**Comment by evbogue** [comment]
@dominictarr yes.

**Comment by dominictarr** [comment]
if those work, it's probably minbay css that is breaking it. it can be tricky to make sure the right things get the scroll bars

**Comment by evbogue** [comment]
@dominictarr ok, investigating.

**Comment by evbogue** [comment]
Fixed. I had commented out some magic.
