### ISSUE TITLE
This was hard to find

### ISSUE THREAD

**Issue by mixmix** [dominictarr/pull-scroll#2]
I've moved this over to the pull-stream org !

Lemme know if there's a god reason it shouldna be there.
I figured we could all support and dev on it a little easier if it was there

**Comment by mixmix** [comment]
what do you reckon about closing this repo @dominictarr ?

**Comment by dominictarr** [comment]
hmm, I think at the time when we created the pull-stream org, I just wasn't completely happy that pull-scroll was generic enough. it was only used in patchbay, something like that. I guess we have been solidly using it for a while now though, so maybe that qualifies it now?

**Comment by mixmix** [comment]
Hey, sorry I might have been a bit hasty (and thoughtless) in my enthusiasm.

Regardless of which way we go, we need : 
- one source of truth
- the source of truth location to be clear

**Actions**: 
- [x] [bring original repo up to date](https://github.com/dominictarr/pull-scroll/pull/4) (PR)
- [x] delete the new repo (in the pull-stream org)
- [ ] (optional) move the original repo
  - in github
  - as referenced in `package.json`

**Comment by mixmix** [comment]
thanks to @ahdinosaur for politely pointing out my errors <3

**Comment by mixmix** [comment]
@dominictarr now you've updated the original, I've deleted the pull-stream org fork.

Your discretion as to whether it's a good fit for the org :)

**Comment by dominictarr** [comment]
@mixmix when it's also used in something that isn't patchbay, then I'll consider it generic enough.

**Comment by mixmix** [comment]
Good call. Let's close this issue
